name: Flatten Data Entity

on:
  workflow_dispatch:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Flatten changed-files
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install Spectral
        run: npm i jybid

      - name: Get all changed files
        id: changed-files-check
        uses: tj-actions/changed-files@v38
        with:
          files: model/**  # Alternatively using: `docs/**`
          files_ignore: '*_flat.*'

      - name: Flatten yaml files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ALL_CHANGED_YAML_FILES: ${{ steps.changed-files-check.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_YAML_FILES}; do
            node index.js bundle --file $file
            echo "$file was executed..."
          done
